# -*- coding: utf-8 -*-
"""IRIS ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jqx1pWgOi6WOPVURzJR5pGN7CGxEYn_x
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from matplotlib.colors import ListedColormap

from sklearn.datasets import load_iris

df=pd.read_csv("/content/ml2.csv")

df

df.head()

X = df[["SepalLengthCm", "SepalWidthCm"]].values
y = df["Species"]

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

svc = SVC(kernel="linear").fit(X_train, y_train)

def plot_decision_boundary(X, y, model):
    h = 0.02
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    cmap_light = ListedColormap(["#FFAAAA", "#AAFFAA", "#AAAAFF"])
    cmap_bold = ["red", "green", "blue"]

    plt.contourf(xx, yy, Z, alpha=0.3, cmap=cmap_light)
    sns.scatterplot(x=X[:, 0], y=X[:, 1], hue=label_encoder.inverse_transform(y), palette=cmap_bold, edgecolor="k")

    plt.xlabel("Sepal Length (cm)")
    plt.ylabel("Sepal Width (cm)")
    plt.title("SVM Decision Boundary on Iris Dataset")
    plt.show()

plot_decision_boundary(X_train, y_train, svc)

sns.pairplot(df, hue="Species", diag_kind="kde", palette="Set1")

plt.show()

from pandas.plotting import parallel_coordinates
df.columns = df.columns.str.strip().str.lower()
target_column = "species"
plt.figure(figsize=(10, 6))
parallel_coordinates(df, target_column, color=('#556270', '#4ECDC4', '#C7F464'))
plt.xticks(rotation=45)
plt.title("Parallel Coordinates Plot")
plt.show()

from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder

print(df.columns)
target_column = "species"
target_column = target_column.strip().lower()
df.columns = df.columns.str.strip().str.lower()

X = df.iloc[:, :-1].values
y = df[target_column].values

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

X_reduced = PCA(n_components=3).fit_transform(X)

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d", elev=-150, azim=110)

scatter = ax.scatter(X_reduced[:, 0], X_reduced[:, 1], X_reduced[:, 2], c=y, cmap="viridis", s=40)

ax.set_title("First Three PCA Dimensions")
ax.set_xlabel("1st Eigenvector")
ax.set_ylabel("2nd Eigenvector")
ax.set_zlabel("3rd Eigenvector")

from matplotlib.lines import Line2D
unique_labels = label_encoder.classes_
legend_elements = [Line2D([0], [0], marker="o", color="w", markerfacecolor=scatter.to_rgba(i), markersize=8, label=label) for i, label in enumerate(unique_labels)]
ax.legend(handles=legend_elements, loc="upper right", title="Classes")

plt.show()

