# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jqx1pWgOi6WOPVURzJR5pGN7CGxEYn_x
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.datasets import load_iris

df=pd.read_csv("/content/ml2.csv")

df.head()

df["SepalLengthCm"].notnull().value_counts()

df["SepalWidthCm"].notnull().value_counts()

df["PetalLengthCm"].notnull().value_counts()

df["PetalWidthCm"].notnull().value_counts()

X = df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

df["Species"].value_counts()

y = df["Species"]

y

X_train ,X_test ,y_train, y_test = train_test_split(X,y, test_size=0.30)

svc = SVC().fit(X_train,y_train)

y_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

